// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz4km49MyHIUTXS8tO7_z087YeWMJ3_eU',
    appId: '1:251363039241:web:b858ee23d84e03fbfa40d8',
    messagingSenderId: '251363039241',
    projectId: 'randomav-57d56',
    authDomain: 'randomav-57d56.firebaseapp.com',
    storageBucket: 'randomav-57d56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQi2scv0RHNUXyIQfF-llTeY71hlU5WEo',
    appId: '1:251363039241:android:c370650098ab29d4fa40d8',
    messagingSenderId: '251363039241',
    projectId: 'randomav-57d56',
    storageBucket: 'randomav-57d56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWJCWSAfonYKkDjpvQJN41Te7uq50ne_U',
    appId: '1:251363039241:ios:807d95b01ec7af3dfa40d8',
    messagingSenderId: '251363039241',
    projectId: 'randomav-57d56',
    storageBucket: 'randomav-57d56.appspot.com',
    iosClientId: '251363039241-kngmcdj130jl58pvb53p3298bbrdst1n.apps.googleusercontent.com',
    iosBundleId: 'com.randomaudiovideo.randomAv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWJCWSAfonYKkDjpvQJN41Te7uq50ne_U',
    appId: '1:251363039241:ios:807d95b01ec7af3dfa40d8',
    messagingSenderId: '251363039241',
    projectId: 'randomav-57d56',
    storageBucket: 'randomav-57d56.appspot.com',
    iosClientId: '251363039241-kngmcdj130jl58pvb53p3298bbrdst1n.apps.googleusercontent.com',
    iosBundleId: 'com.randomaudiovideo.randomAv',
  );
}
